# Generated by Django 4.1.1 on 2022-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userbookrelation_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookrelation',
            name='discount',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
